import "./globals.css";
import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body>
        <Providers>
          <div className="container h-[calc(100vh_-_var(--vh-offset,_0px))] m-auto">
            {children}
          </div>
        </Providers>
        <Analytics />
      </body>
    </html>
  );
}
